[workspace]
resolver = "3"
members = ["app/src-tauri","library/ftc-emu-core"]

[workspace.dependencies]
ftc-emu-core = { path = "library/ftc-emu-core"}

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
