[workspace]
resolver = "3"
members = ["ftc-emu","library/ftc-emu-core"]

[workspace.dependencies]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
